-- Phase 4A: buyer/seller transaction foundation.
--
-- The orders/order_items/payments/commissions schema, every relevant
-- enum, and every SELECT RLS policy already existed from the foundation
-- phase (see 20260920090500_orders_payments.sql,
-- 20260920090400_commerce_config.sql, 20260920091500_rls_policies.sql) —
-- inspected first, nothing duplicated here. Two things were actually
-- missing:
--
-- 1. A public-safe order reference. `orders.id` is a UUID — fine as a
--    primary key, not something to read aloud or put in a URL a buyer
--    screenshots. `order_reference` gets a column DEFAULT (not
--    generated by application code) so every future INSERT gets one
--    automatically, including the raw fixture INSERT in
--    tests/db/rls.test.ts, which predates this column and doesn't
--    mention it.
--
-- 2. The order-creation transaction itself. Placing an order touches six
--    things that must all succeed or all fail together: flip the
--    product from published to sold (the overselling/idempotency
--    guard — see below), insert the order, its order_item, its payment,
--    its commission, and its ORDER_CREATED transaction_event. The
--    Supabase JS client has no way to wrap several separate `.from()`
--    calls in one transaction; a single PL/pgSQL function is the
--    established way this codebase already solves exactly this shape of
--    problem (see search_nearby_products()) — one function body is one
--    transaction. It's SECURITY DEFINER for a concrete, necessary
--    reason: none of orders/order_items/payments/commissions/
--    transaction_events has an INSERT policy for `authenticated` at all
--    (every write to them is meant to be server-side only — see the RLS
--    migration's own header comment), and a buyer has no ownership-based
--    UPDATE grant on a product they don't own. A non-definer function
--    would fail at the very first statement. Ownership/authorization are
--    still fully validated *inside* the function body from auth.uid()
--    (never a parameter) — SECURITY DEFINER only removes the RLS
--    obstacle to the writes this function itself has already decided are
--    legitimate, it doesn't skip any check.
--
-- Overselling AND duplicate-submission protection, with one mechanism:
-- `update products set status = 'sold' where id = ... and status =
-- 'published'`. Postgres locks the target row for the duration of the
-- UPDATE; two concurrent callers targeting the same product serialize on
-- that lock, and whichever runs second re-evaluates the WHERE clause
-- against the first caller's now-committed 'sold' status and matches
-- zero rows — verified against a real engine in tests/db/orders.test.ts,
-- not assumed from reading the SQL. A buyer double-clicking "Buy now", a
-- retried network request, and two different buyers racing for the same
-- listing are all the same case to this guard: whoever's UPDATE commits
-- first gets the order, everyone else gets a clean "not available"
-- error, never a second successful order for the same listing.
alter table public.orders
  add column order_reference text not null unique
  default ('BMB-' || upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 6)));

create function public.create_order(
  p_product_id uuid,
  p_fulfilment_type fulfilment_type
)
returns table (order_id uuid, order_reference text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_buyer_id uuid := auth.uid();
  v_seller_type seller_type;
  v_seller_profile_id uuid;
  v_business_id uuid;
  v_title text;
  v_price_cents bigint;
  v_currency text;
  v_collection_available boolean;
  v_delivery_available boolean;
  v_rate_bps integer;
  v_commission_cents bigint;
  v_provider_id uuid;
  v_delivery_location_id uuid;
  v_order_id uuid;
  v_order_reference text;
begin
  if v_buyer_id is null then
    raise exception 'Authentication required';
  end if;

  -- The atomic reserve-and-validate-availability step. Schema-qualified,
  -- no unqualified identifier the caller could ever influence.
  update public.products
  set status = 'sold'
  where id = p_product_id and status = 'published'
  returning seller_type, seller_profile_id, business_id, title, price_cents, currency,
    collection_available, delivery_available
  into v_seller_type, v_seller_profile_id, v_business_id, v_title, v_price_cents, v_currency,
    v_collection_available, v_delivery_available;

  if not found then
    raise exception 'Product is not available for purchase';
  end if;

  if v_seller_type = 'parent' and v_seller_profile_id = v_buyer_id then
    raise exception 'Cannot buy your own listing';
  end if;
  if v_seller_type = 'business' and public.is_business_member(v_business_id) then
    raise exception 'Cannot buy your own listing';
  end if;

  if p_fulfilment_type = 'collection' and not v_collection_available then
    raise exception 'Collection is not available for this listing';
  end if;
  if p_fulfilment_type = 'delivery' and not v_delivery_available then
    raise exception 'Delivery is not available for this listing';
  end if;

  -- Delivery destination is the buyer's own saved location (Phase 3B
  -- infrastructure — see profiles.location_id) — never a client-supplied
  -- id, so no ownership check is needed the way products.pickup_location_id
  -- needed one: this value comes from the caller's own profile row, which
  -- they can only ever point at a location they created (see
  -- 20260924090000_location_ownership_review_fixes.sql).
  if p_fulfilment_type = 'delivery' then
    select location_id into v_delivery_location_id from public.profiles where id = v_buyer_id;
    if v_delivery_location_id is null then
      raise exception 'Set your delivery location before checking out';
    end if;
  end if;

  -- Current commission rate for this seller_type — commission_rates is
  -- an append-only history (see 20260920090400_commerce_config.sql); the
  -- "current" rate is the latest row already in effect.
  select rate_bps into v_rate_bps
  from public.commission_rates
  where seller_type = v_seller_type and effective_from <= now()
  order by effective_from desc
  limit 1;

  if v_rate_bps is null then
    raise exception 'No commission rate configured for this seller type';
  end if;

  -- Integer-cents rounding, same half-up convention as calculateCommission()
  -- in src/server/commission/calculateCommission.ts — this function is the
  -- database-side mirror of that pure function, not a second, drifting
  -- implementation of the same formula (bps/10000 either way).
  v_commission_cents := round((v_price_cents * v_rate_bps) / 10000.0);

  select id into v_provider_id from public.payment_providers where slug = 'mock' and is_active limit 1;
  if v_provider_id is null then
    raise exception 'Payment processing is not currently available';
  end if;

  insert into public.orders (
    buyer_id, seller_type, seller_profile_id, business_id, fulfilment_type, payment_method, status,
    subtotal_cents, delivery_fee_cents, total_cents, commission_rate_bps, commission_amount_cents,
    currency, delivery_location_id
  ) values (
    v_buyer_id, v_seller_type, v_seller_profile_id, v_business_id, p_fulfilment_type, 'online', 'pending_payment',
    v_price_cents, 0, v_price_cents, v_rate_bps, v_commission_cents,
    v_currency, v_delivery_location_id
  )
  returning id, orders.order_reference into v_order_id, v_order_reference;

  insert into public.order_items (order_id, product_id, title_snapshot, price_cents_snapshot, quantity)
  values (v_order_id, p_product_id, v_title, v_price_cents, 1);

  insert into public.payments (order_id, provider_id, method, status, amount_cents, currency)
  values (v_order_id, v_provider_id, 'online', 'pending', v_price_cents, v_currency);

  insert into public.commissions (order_id, seller_type, rate_bps, base_amount_cents, commission_amount_cents)
  values (v_order_id, v_seller_type, v_rate_bps, v_price_cents, v_commission_cents);

  insert into public.transaction_events (order_id, entity_type, entity_id, event_type, actor_type, actor_id, payload)
  values (
    v_order_id, 'order', v_order_id, 'order.created', 'buyer', v_buyer_id,
    jsonb_build_object(
      'product_id', p_product_id,
      'order_reference', v_order_reference,
      'fulfilment_type', p_fulfilment_type,
      'subtotal_cents', v_price_cents,
      'commission_rate_bps', v_rate_bps,
      'commission_amount_cents', v_commission_cents
    )
  );

  return query select v_order_id, v_order_reference;
end;
$$;

-- Buyers only — a signed-out visitor has nothing to buy with, and the
-- function's own auth.uid() check would reject them anyway; restricting
-- the grant is defense in depth, not the only check. CREATE FUNCTION
-- grants EXECUTE to PUBLIC by default (unlike tables/views), and this
-- project's default privileges additionally grant EXECUTE on every new
-- public-schema function to anon/authenticated/service_role as soon as
-- it's created (mirrors what a real Supabase project provisions) — both
-- are revoked explicitly rather than left in place, per the Phase 3B
-- security review's "EXECUTE permissions are explicitly appropriate"
-- finding (see DECISIONS.md and 20260924090000_location_ownership_review_fixes.sql).
-- anon has no legitimate reason to ever call this — there is no
-- anonymous buyer identity to attach an order to.
revoke execute on function public.create_order(uuid, fulfilment_type) from public;
revoke execute on function public.create_order(uuid, fulfilment_type) from anon;
grant execute on function public.create_order(uuid, fulfilment_type) to authenticated;
